my_blog:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix:   /my_blog

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

nik_home1:
    resource: "@NikHome1Bundle/Resources/config/routing.yml"
    prefix:   /

nik_blog:
    resource: "@NikBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
