my_blog_homepage:
    path:     /
    defaults: { _controller: MyBlogBundle:Public:index }

my_blog_page:
    path:     /page/{page}
    defaults: { _controller: MyBlogBundle:Public:page }
    requirements:
         page: \d+
    

my_blog_article:
    path:     /article/{slug}.{_format}
    defaults: { _controller: MyBlogBundle:Public:article, _format: html }
    requirements:
         _format: html
         